### ISSUE TITLE
Can I have a water?

### ISSUE THREAD

**Issue by Courtsilius** [Jakob-117/Rust-Kurs-Tuebingen#2]
Please?

**Comment by Courtsilius** [comment]
@Jakob-117 this issue seems to not have been resolved yet, is there a ETA on this?

**Comment by Jakob-117** [comment]
![hand-hold-a-glass-of-water-on-white-backgrounds-isolated-picture-id696959154-804224285](https://github.com/Jakob-117/rust-kurs-tuebingen/assets/63905098/d73ffa05-e923-406e-8b33-7cf6fc8fa82a)

Here you go :)
